<?php 

    session_start();

    if (isset($_SESSION["heroName"])) {
        $heroName = $_SESSION["heroName"];
    } else {
        $heroName = "Héro";
    }
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>
        Le site dont vous êtes le héros
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css" />
</head>
<body id="choice-dark-blue">
<main>
    <section>
        <h2>FIN</h2>
               <div>
                    <h2>Continuez à forger votre destin de mage légendaire.<br>
                    Félicitations <?php echo $heroName ?>,<br>vous avez atteint l'une des Fins Héroïques</h1>
                </div>
    </section>
    <section>
        <section>
            <img src="assets/img/fire-spell.png" />
            <h1>Avec vos nouvelles compétences en magie ancienne,<br> vous parcourez le monde en aidant les gens et en combattant les forces du mal.<br>Votre légende grandit</h1>
        </section>
    </section>
</main>
<script type="application/javascript" src="assets/js/index.js"></script>
</body>
</html>