<?php 
    session_start();

    if (isset($_SESSION["heroName"])) {
        $heroName = $_SESSION["heroName"];
    } else {
        $heroName = "Héro";
    }
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>
        Le site dont vous êtes le héros
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css" />
</head>
<body id="choice-dark-blue">
<main>
    <section>
        <h2>FIN</h2>
        <div>
            <h2>Vivez paisiblement dans le Royaume des Elfes.<br>
            Félicitations <?php echo $heroName ?>,<br>vous avez atteint l'une des Fins Enchantées</h2>
        </div>
    </section>
    <section>
        <section>
            <img src="assets/img/potion.png" />
            <h1>Vous choisissez de rester un moment dans le Royaume des Elfes, où vous êtes accueilli comme un héros.<br>Vous vivez en harmonie avec la nature</h1>
        </section>
    </section>
</main>
<script type="application/javascript" src="assets/js/index.js"></script>
</body>
</html>