<?php 
if (isset($_GET["heroName"])) {
    $heroName = $_GET["heroName"];
} else {
    $heroName = "Héro";
}
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>
        Le site dont vous êtes le héros
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css" />
</head>
<body id="choice-dark-blue">
<main>
    <section>
        <h2>FIN</h2>
        <div>
             <h2>Explorez le monde avec votre nouvel artefact.<br>
             Félicitations <?php echo $heroName ?>, vous avez atteint l'une des Fins Puissantes</h2>
        </div>
    </section>
    <section>
        <section>
            <img src="assets/img/fire-spell.png" />
            <h1>Vous avez accompli la mission des esprits avec succès.<br>En retour, ils vous remettent un artefact puissant qui vous confère des pouvoirs extraordinaires</h1>
        </section>
    </section>
</main>
<script type="application/javascript" src="assets/js/index.js"></script>
</body>
</html>