<?php

    session_start();
    
    if (isset($_GET["heroName"])) {
        $_SESSION["heroName"] = $_GET["heroName"];
        $heroName = $_SESSION["heroName"];
    } else {
        $heroName = "Héro";
    }
    
    if ($_SERVER["REQUEST_METHOD"] === "GET") {

        if(isset($_GET["choice"])) {
            $choice = $_GET["choice"];

            if ($choice === "choice-1") {
                header("Location: page-7.phtml"); // Redirige vers la page 7
                exit();
            } elseif ($choice === "choice-2") {
                header("Location: page-8.phtml"); // Redirige vers la page 8
                exit();
            }
        }
    }
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>
        Le site dont vous êtes le héros
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css" />
</head>
<body id="choice-dark-blue">
<main>
    <section>
        <h2>Description du choix à faire</h2>
        <div>
            <form method="get" action="">
                <div>
                    <input type="radio" id="choice-1" name="choice" value="choice-1">
                    <label for="choice-1">Aidez l'elfe à protéger l'Arbre du Monde</label>
                </div>
                <div>
                    <input type="radio" id="choice-2" name="choice" value="choice-2">
                    <label for="choice-2">Ignorez l'elfe et continuez votre chemin</label>
                </div>
                <div>
                    <input type="submit" value="Valider le choix" />
                </div>
            </form>
        </div>
    </section>
    <section>
        <section>
            <img src="assets/img/elf.png" />
            <h1>Vous traversez le pont en bois et entrez dans le Royaume des Elfes, où la nature semble vivante. Un elfe vous approche avec une requête</h1>
        </section>
    </section>
</main>
<script type="application/javascript" src="assets/js/index.js"></script>
</body>
</html>