<?php
    session_start();
    
    if (isset($_GET["heroName"])) {
        $_SESSION["heroName"] = $_GET["heroName"];
        $heroName = $_SESSION["heroName"];
    } else {
        $heroName = "Héro";
    }


    if ($_SERVER["REQUEST_METHOD"] === "GET") {

        if(isset($_GET["choice"])) {
            $choice = $_GET["choice"];

            if ($choice === "choice-1") {
                header("Location: page-2.phtml"); // Redirige vers la page 2
                exit();
            } elseif ($choice === "choice-2") {
                header("Location: page-3.phtml"); // Redirige vers la page 3
                exit();
            } elseif ($choice === "choice-3") {
                header("Location: page-4.phtml"); // Redirige vers la page 4
                exit();
            }
        }
    }
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>
        Le site dont vous êtes le héros
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css" />
</head>
<body id="choice">
<main>
    <section>
        <h2>Description du choix à faire</h2>
        <div>
            <form method="GET" action="<?php echo $_SERVER['PHP_SELF']; ?>">
                <div>
                    <input type="radio" id="choice-1" name="choice" value="choice-1">
                    <label for="choice-1">Pour emprunter le sentier escarpé menant à la Tour des Mystères</label>
                </div>
                <div>
                    <input type="radio" id="choice-2" name="choice" value="choice-2">
                    <label for="choice-2">Vous choisissez de traverser le pont en bois menant au Royaume des Elfes</label>
                </div>
                <div>
                    <input type="radio" id="choice-3" name="choice" value="choice-3">
                    <label for="choice-3">Pour explorer le sentier caché derrière les chutes d'eau menant à la Grotte des Anciens</label>
                </div>
                <div>
                    <input type="submit" value="Valider le choix" />
                </div>
            </form>
        </div>
    </section>
    <section>
        <section>
            <img src="assets/img/door.png" />
            <h1>Vous vous tenez à un croisement, face à un choix crucial. Trois routes s'offrent à vous. Où déciderez-vous de vous aventurer ?</h1>
        </section>
    </section>
</main>
<script type="application/javascript" src="assets/js/index.js"></script>
</body>
</html>