<?php

    $heroName = $_GET["heroName"];
    
    if ($_SERVER["REQUEST_METHOD"] === "GET") {

        if(isset($_GET["choice"])) {
            $choice = $_GET["choice"];

            if ($choice === "choice-1") {
                header("Location: page-1.phtml"); // Redirige vers la page 1
                exit();
            }
        }
    }
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>
        Le site dont vous êtes le héros
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css" />
</head>
<body id="choice-red">
<main>
    <section>
        <h2>Description du choix à faire</h2>
        <div>
            <form method="get" action="">
                <div>
                    <input type="radio" id="choice-1" name="choice" value="choice-1">
                    <label for="choice-1">Choisissez une nouvelle direction</label>
                </div>
                <div>
                    <input type="submit" value="Valider le choix" />
                </div>
            </form>
        </div>
    </section>
    <section>
        <section>
            <img src="assets/img/treasure.png" />
            <h1>Vous décidez de ne pas prendre de risque et de quitter la grotte sans rien prendre. Vous retournez au croisement</h1>
        </section>
    </section>
</main>
<script type="application/javascript" src="assets/js/index.js"></script>
</body>
</html>